name: BLOG_API CI/CD

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            cd /var/www/blog_nuxt
            git pull origin production
            git status
            npm install
            npm run build:production
            pm2 restart ./ecosystem.config.production.cjs